### PR TITLE
[testing] fix rubocop errors in CI files

### LINKED ISSUE #1622: [activemq] fix ci file
Rubocop and formatting changed.

### PR DESCRIPTION
**Pull request by LeoCavaille**
Fixes #1622

### CODE REVIEW

File: ci/activemq.rb [hunk 1]
```diff
@@ -9,10 +9,10 @@ def activemq_rootdir
 end
 
 namespace :ci do
-  namespace :activemq do |flavor|
-    task :before_install => ['ci:common:before_install']
+  namespace :my_new_flavor do |flavor|
```
Comment (degemer) [inline ci/activemq.rb]: Bad c/p, it should be `:activemq`.

File: ci/common.rb [hunk 2]
```diff
@@ -158,16 +158,16 @@ def self.for(smth, max_timeout = DEFAULT_TIMEOUT)
     task :run_tests, :flavor do |t, attr|
       flavors = attr[:flavor]
       filter = ENV['NOSE_FILTER'] || '1'
-      if flavors.include? 'default' or flavors.include? 'checks_mock'
+      if flavors.include? 'default' || flavors.include? 'checks_mock'
```
Comment (degemer) [inline ci/common.rb]: `||` has a stronger precedence than `or`, you should add parenthesis: `flavors.include?('default')`.

**Comment by degemer** [comment]
Nice cleanup! :gem: 
Maybe we could enforce this "good behavior" by using https://github.com/bbatsov/rubocop#rake-integration (we can probably do it in another PR).

File: Rakefile [hunk 3]
```diff
@@ -92,7 +93,9 @@ namespace :test do
 end
 
 desc 'Lint the code through pylint'
-task 'lint' => 'ci:default:lint'
+task 'lint' => ['ci:default:lint'] do
+  sh 'rubocop --fail-level W'
```
Comment (degemer) [inline Rakefile]: Why not create a custom Rake task instead and invoke it here ? (and so delete the `RuboCop::RakeTask.new`)
```
require 'rubocop/rake_task'

desc 'Run RuboCop on the ci directory'
RuboCop::RakeTask.new(:rubocop) do |task|
  task.patterns = ['ci/**/*.rb', 'Gemfile, 'Rakefile']
end
```

Comment (degemer) [inline Rakefile]: Instead of `--fail-level W`, could you instead create a `.rubocop.yml` file to only ignore specific errors ? You can generate one with `rubocop --auto-gen-config`.

**Comment by degemer** [comment]
Awesome ! :clap: 
@yannmh won't have any excuse next time !

File: Rakefile (hunk 3 above)
Comment (LeoCavaille) [inline Rakefile]: Nice for the rake task! Will fix.
Forgot to stage the rubocop yaml file :fearful:
