### PR TITLE
[k8s/docker] Better support of kubernetes >= 1.2

### LINKED ISSUE #2263: Incorrect detection of pods managed by a kubelet
```
ERROR (__init__.py:762): Check 'kubernetes' instance #0 failed
 Traceback (most recent call last):
   File "/opt/datadog-agent/agent/checks/__init__.py", line 745, in run
     self.check(copy.deepcopy(instance))
   File "/opt/datadog-agent/agent/checks.d/kubernetes.py", line 150, in check
     self._update_metrics(instance, kube_settings)
   File "/opt/datadog-agent/agent/checks.d/kubernetes.py", line 240, in _update_metrics
     kube_labels = self._retrieve_kube_labels()
   File "/opt/datadog-agent/agent/checks.d/kubernetes.py", line 235, in _retrieve_kube_labels
     return get_kube_labels()
   File "/opt/datadog-agent/agent/utils/kubeutil.py", line 53, in get_kube_labels
     for pod in pods["items"]:
 TypeError: 'NoneType' object is not iterable
```

because:

```
[root@minion0 vagrant]# curl -s http://localhost:10255/pods
{"kind":"PodList","apiVersion":"v1","metadata":{},"items":null}
```

```
[root@minion0 vagrant]# cat /etc/dd-agent/conf.d/kubernetes.yaml
init_config:

instances:
  - host: localhost
    port: 4194
    method: http
    use_histogram: true
    enable_kubelet_checks: true
    kubelet_port: 10255
```

### LINKED ISSUE #2388: 5.7.1 does not work with Kubernetes 1.2
I was able to track it down to the labels the kubelet adds to the containers and are exposed via cadvisor inside the kubelet.  in 1.1, we get labels like:

```
  "io.kubernetes.pod.terminationGracePeriod": "60",
  "io.kubernetes.pod.name": "cluster/kube-datadog-cpwwj"
```

in 1.2, we get:

```
"io.kubernetes.container.hash": "d6fe00ff",
  "io.kubernetes.container.name": "POD",
  "io.kubernetes.container.restartCount": "0",
  "io.kubernetes.container.terminationMessagePath": "",
  "io.kubernetes.pod.name": "fluentd-melvb",
  "io.kubernetes.pod.namespace": "cluster",
  "io.kubernetes.pod.terminationGracePeriod": "60",
  "io.kubernetes.pod.uid": "4fec2f14-f2e0-11e5-9e88-42010af20017"
```

I'm playing with a quick patch, but there's probably a more elegant way.

### LINKED ISSUE #2444: [kubernetes] add replicaset pods to kubernetes.pods.running metric
In PR #2277 @masci created the basics for the pod counts based on ReplicaControllers 🏆 . Since the release of Kubernetes (k8s) 1.2 this is no longer enough. The developers introduced `Deployments` in k8s 1.2 which work in combination with [`ReplicaSets`](http://kubernetes.io/docs/user-guide/replication-controller/#replicaset) instead of `ReplicaControllers` thus having pods be annotated as created-by `ReplicaSet`. 

## Proposed change

The pods are grouped by creator name in [`/checks.d/kubernetes.py`](https://github.com/DataDog/dd-agent/blob/master/checks.d/kubernetes.py#L246). Proposed change is to have this grouping also include pods grouped by ReplicaSet. As far as i can see the naming of ReplicationControllers/ReplicaSets is unique so no overlap should be possible.

## Example annotation output with new ReplicaSets:

```
"annotations": {
  "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"default\",\"name\":\"myreplicaset-2962775361\",\"uid\":\"618e8a0a-07c3-11e6-855b-42010af00104\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"3428\"}}\n"
}
```

This ticket has been created while using Kubernetes version 1.2.2

### PR DESCRIPTION
**Pull request by remh**
- Enable kubelet check by default
- Remove master check for now as they are flaky, hard to enable and not used
- Adapt to new format of labels set by kube1.2 fix #2388 #2494
- Allow to blacklist labels
- Support replica sets fix #2444 #2446
- Handle case where no pods are running. Fix #2263
- Add tests for kube 1.2

### CODE REVIEW

File: checks.d/kubernetes.py [hunk 1]
```diff
@@ -46,6 +46,10 @@
     RATE: {True: HISTORATE, False: RATE}
 }
 
+POD_NAME_LABEL = "io.kubernetes.pod_name"
+NAMESPACE_LABEL = "io.kubernetes.pod.namespace"
```
Comment (hkaj) [inline checks.d/kubernetes.py]: I think we should create a dict of labels in `kubeutil` and import it when needed. These 2 are also in `checks.d/docker_daemon.py` and we'll probably add more in the future. It would be better to have them all in a single place.

**Comment by hkaj** [comment]
also tests are failing:
```
test_historate_1_1 (tests.checks.mock.test_kubernetes.TestKubernetes) ... FAIL
test_historate_1_2 (tests.checks.mock.test_kubernetes.TestKubernetes) ... FAIL
test_metrics_1_1 (tests.checks.mock.test_kubernetes.TestKubernetes) ... FAIL
test_metrics_1_2 (tests.checks.mock.test_kubernetes.TestKubernetes) ... FAIL
```

**Comment by hkaj** [comment]
LGTM
